#cmake -DCMAKE_CXX_STANDARD=17 -DSYCL_INTEL_TARGET=ON -DENABLE_INTEL_XMX=ON -DCUTLASS_ENABLE_SYCL=ON -DCOMPUTE_BACKEND=xpu -S .
#cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS_DEBUG="-O0 -g" -DCMAKE_CXX_STANDARD=17 -DSYCL_INTEL_TARGET=ON -DENABLE_INTEL_XMX=ON -DCUTLASS_ENABLE_SYCL=ON -DCOMPUTE_BACKEND=xpu -S .
#cmake -DCOMPUTE_BACKEND=xpu -DCMAKE_BUILD_TYPE=Debug -DCMAKE_CXX_FLAGS_DEBUG="-O0 -g" -S .
#cmake --build . --config Release -j
#cmake -DCMAKE_CXX_STANDARD=17 -DSYCL_INTEL_TARGET=ON -DENABLE_INTEL_XMX=ON -DCUTLASS_ENABLE_SYCL=ON -DCOMPUTE_BACKEND=xpu -S .
cmake  -DSYCL_INTEL_TARGET=ON -DENABLE_INTEL_XMX=ON -DCUTLASS_ENABLE_SYCL=ON -DCOMPUTE_BACKEND=xpu -S .
make
pip install -e .
